import SwiftUI

struct SubtitleTrackListView: View {
    let project: Project
    @Environment(\.modelContext) private var modelContext
    @State private var showImporter = false

    private var sortedTracks: [SubtitleTrack] {
        project.subtitleTracks.sorted { a, b in
            if a.isPrimary != b.isPrimary { return a.isPrimary }
            return a.fileName < b.fileName
        }
    }

    var body: some View {
        List {
            if sortedTracks.isEmpty {
                ContentUnavailableView(
                    "No Subtitles",
                    systemImage: "captions.bubble",
                    description: Text("Import an SRT or VTT file, or auto-generate from speech.")
                )
            } else {
                ForEach(sortedTracks) { track in
                    SubtitleTrackRow(track: track) {
                        setPrimary(track)
                    }
                }
                .onDelete(perform: deleteTracks)
            }
        }
        .navigationTitle("Subtitles")
        .toolbar {
            ToolbarItem(placement: .topBarLeading) {
                Button {
                    showImporter = true
                } label: {
                    Image(systemName: "plus")
                }
            }
        }
        .fileImporter(
            isPresented: $showImporter,
            allowedContentTypes: [.plainText],
            allowsMultipleSelection: false
        ) { result in
            switch result {
            case .success(let urls):
                guard let url = urls.first else { return }
                do {
                    _ = try SubtitleImportService.importSubtitleFile(
                        from: url,
                        for: project,
                        modelContext: modelContext
                    )
                } catch {
                    print("Subtitle import failed: \(error)")
                }
            case .failure(let error):
                print("File picker error: \(error)")
            }
        }
    }

    private func setPrimary(_ track: SubtitleTrack) {
        for t in project.subtitleTracks {
            t.isPrimary = (t.id == track.id)
        }
    }

    private func deleteTracks(at offsets: IndexSet) {
        let tracks = sortedTracks
        for index in offsets {
            modelContext.delete(tracks[index])
        }
    }
}

struct SubtitleTrackRow: View {
    let track: SubtitleTrack
    let onSetPrimary: () -> Void

    var body: some View {
        HStack {
            VStack(alignment: .leading, spacing: 4) {
                HStack(spacing: 6) {
                    Text(track.fileName)
                        .font(.body)
                        .lineLimit(1)

                    if track.isAutoGenerated {
                        Text("Auto")
                            .font(.caption2)
                            .padding(.horizontal, 5)
                            .padding(.vertical, 2)
                            .background(.blue.opacity(0.15))
                            .foregroundStyle(.blue)
                            .clipShape(Capsule())
                    }
                }

                HStack(spacing: 8) {
                    Text(Locale.current.localizedString(forLanguageCode: track.language) ?? track.language)
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    Text("\(track.cues.count) cues")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            Spacer()

            if track.isPrimary {
                Image(systemName: "checkmark.circle.fill")
                    .foregroundStyle(.tint)
            } else {
                Button {
                    onSetPrimary()
                } label: {
                    Image(systemName: "circle")
                        .foregroundStyle(.secondary)
                }
                .buttonStyle(.plain)
            }
        }
        .padding(.vertical, 2)
    }
}
