import Foundation
import SwiftData

@Model
final class SubtitleTrack {
    @Attribute(.unique) var id: UUID
    var fileName: String
    var language: String
    var isPrimary: Bool
    var isAutoGenerated: Bool

    @Relationship(deleteRule: .cascade, inverse: \SubtitleCue.track)
    var cues: [SubtitleCue]

    var project: Project?

    init(
        fileName: String,
        language: String = "en",
        isPrimary: Bool = true,
        isAutoGenerated: Bool = false
    ) {
        self.id = UUID()
        self.fileName = fileName
        self.language = language
        self.isPrimary = isPrimary
        self.isAutoGenerated = isAutoGenerated
        self.cues = []
    }
}
