import Foundation
import SwiftData

struct SubtitleImportService {
    static func importSubtitleFile(
        from sourceURL: URL,
        for project: Project,
        modelContext: ModelContext
    ) throws -> SubtitleTrack {
        let accessing = sourceURL.startAccessingSecurityScopedResource()
        defer {
            if accessing {
                sourceURL.stopAccessingSecurityScopedResource()
            }
        }

        let ext = sourceURL.pathExtension.lowercased()
        let fileName = sourceURL.deletingPathExtension().lastPathComponent

        let parsedCues: [(index: Int, start: TimeInterval, end: TimeInterval, text: String)]

        switch ext {
        case "srt":
            let cues = try SRTParser.parse(from: sourceURL)
            parsedCues = cues.map { (index: $0.index, start: $0.startTime, end: $0.endTime, text: $0.text) }
        case "vtt":
            let cues = try VTTParser.parse(from: sourceURL)
            parsedCues = cues.map { (index: $0.index, start: $0.startTime, end: $0.endTime, text: $0.text) }
        default:
            throw SubtitleImportError.unsupportedFormat(ext)
        }

        guard !parsedCues.isEmpty else {
            throw SubtitleImportError.noCuesFound
        }

        // Detect language from filename (e.g., "audio.en.srt" or "audio_english.srt")
        let language = detectLanguage(from: fileName)

        // Set existing tracks as non-primary
        let isPrimary = project.subtitleTracks.isEmpty
        if isPrimary {
            for track in project.subtitleTracks {
                track.isPrimary = false
            }
        }

        let track = SubtitleTrack(
            fileName: sourceURL.lastPathComponent,
            language: language,
            isPrimary: isPrimary,
            isAutoGenerated: false
        )
        track.project = project
        modelContext.insert(track)

        for parsed in parsedCues {
            let cue = SubtitleCue(
                index: parsed.index,
                startTime: parsed.start,
                endTime: parsed.end,
                text: parsed.text
            )
            cue.track = track
            modelContext.insert(cue)
        }

        try modelContext.save()
        return track
    }

    private static func detectLanguage(from fileName: String) -> String {
        let lower = fileName.lowercased()
        let languageCodes = [
            "en": ["english", ".en", "_en"],
            "es": ["spanish", "espanol", ".es", "_es"],
            "fr": ["french", "francais", ".fr", "_fr"],
            "de": ["german", "deutsch", ".de", "_de"],
            "it": ["italian", "italiano", ".it", "_it"],
            "pt": ["portuguese", ".pt", "_pt"],
            "ja": ["japanese", ".ja", "_ja"],
            "ko": ["korean", ".ko", "_ko"],
            "zh": ["chinese", ".zh", "_zh"],
            "ru": ["russian", ".ru", "_ru"],
            "ar": ["arabic", ".ar", "_ar"],
        ]

        for (code, patterns) in languageCodes {
            for pattern in patterns {
                if lower.contains(pattern) { return code }
            }
        }

        return "en"
    }

    enum SubtitleImportError: Error, LocalizedError {
        case unsupportedFormat(String)
        case noCuesFound

        var errorDescription: String? {
            switch self {
            case .unsupportedFormat(let ext):
                return "Unsupported subtitle format: .\(ext)"
            case .noCuesFound:
                return "No subtitles found in file"
            }
        }
    }
}
